apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    server.secretkey: AgBnOmWx5ehUjrc6PRfhJU1huGoYdA2/EpSTEnoEoS/y/Hrlnqm/obRKEnHh1qJu+vSFyJ316E0U1ND4rbtZ/Ou1Hs27poCJR/Bb/xj0G6KOGbvBnIrf1faOHcxTC3bzKJkyyVdFMyex9sNG9K/JVs9RByWIfAUCq2SwDr8gfcl0hd7aayYvZLqiCheqmsAEi0PIAYi+Jk5PPsf+Ka+k5/2BsHS6H2dG2oCUxjvmbGog3R/GjCq1tQErEZ4hNohWpudelbaKBqu83sD+heFEtQQIvCTtQ3Nrcrcj/vFdU/eZycxDqEHuqiq5Wy9PMYaB79kUb2luDXknSSG377cPIZSB80QCsdfsjuA5ApoAgCm+omz1mnIa4E/N7eeahGcaAz6kJmyDg4dQ/6mhSua2LyY2BTDFlWGgN/CMw7giGff8g3QBshN29993alAmmgpm/xHhughKj/zac3gRklSRIG7izl8sZa+/0vPAOO+QNGSQCPTtAprwoqYdjvRpQVVGpVM6My58Sqx2Edw6kTgqZNq5jCXNUYEjnAQBJOAhaRT000jt6D1BzC9EJ5aAqvqaue/ZGXLdoLBc4kJJdfKCmHlcJaOqX2ph63dM/8GlsBUYMrkQtXlTJGAbpibr4Qq61m/NUoX3/wz23o+xo1BDtGhcsLVQCHStDzevh511MWO0HxVO8behWfIsr0bdhpOtwj/E0ofTjB8CAcWFlK4X3oFL7YTA75m0AZ4=
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
