---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    server.secretkey: AgBpssgFFuxJyptFbfdcMPWzUQ3k+x8eJedtYI+HXo+ojJjtWh2LCEcS0KJA38TA6QSvU7fu0n3ZTKbYJKUjE8KowClpyotdCRvnS9nqUd/hLhs/yySkCTlT2ObIGWM2L0yPKoDtc/VZGtKOLlAQOmT7RS0nBZ7VBXLd2fsTuZr5otISWOAnVzgtgFwzYfZv0UY/Xi8TsladCyX1obp4dc+uHrAmwzzO/h91TzLe1lJLH3TaD+wNAuf9wGtLrLdjnoj/pCsq3lmU2lq61GbntbKet06E/aZndG2viPdadE6WKQRykyn5Qyjsic4dNL6tsxkjiY37mDIcPLnIbfHxToO1paeNIBY3RQjtpOMJF/1iETmOByZjVNy6NGN3sf09NNIWWLTKVBfDj9ILv3A8VPq3QB7xvtSEzavWKEIsQe7s3hmu0auXbK1ez8wN5ljnSZIjkdbKe6NzlpN7J9qVr5tgL0FRGF3vE9VElFuJde1/A1/vIiWmNDhXsZ1xeBJAY99bQzg+uZCAAQUYWjOAALcC20OubFRs4uWuRFgPNpPL3Gcu1LWqLk0H9qfH7IblBTABYXPzIVJ/7MzeC4FIXwQwg1QfjZaqA0qW1VB5rbNw+N3Xtqp4gfhVrOl0PliWi2n7atMdyZzScX+KUZ5fHlEWGelqVtxkwQGaTRJQqy+UxHXk179yH7veG8TY6uhwHeCLLd3oxe9hAfQIr+SXOLun0jfH0xggjm8=
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
