---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    server.secretkey: AgA+hWg1uKLSraNteM2mbjypvb/6dktImfEKR7oc07nH/DD5YkIzVIJBMTYPlxNjjt3JxXO/zMxkpvSyFMnj1G67ZxjuCNUgp6Qha8W2DBLwoov0Jp3icOHPwYFJzbnS9/uLlDinfsEp/HP4C5rzYWH2aBZQ8HOHt/49WU77gwvQljvmxvZtbIvcDUtuZgMFDaZka/UyZWuuklgM4diObXM5+ESH4C/1S2331E1RulnDfmFR4cdDyGGFvHIEfn7/kFbUg6lNhUG1imM8/i3V+8Zt7xLKG58yGLhpQmiDlD+omPPwqZEenqFKFi6As4D6SpdYO+wIly2Y7v6TR0tRkTF0U3c2cd6fZ/2CfaiTLOvBmCsFWr+bREQpXtSOjfgFi3SSQDGCg7hcx9hlg+rjtzprKP26ag1ujG/w2VvysV/hEoy/vi3oxQVrctmxuxDMn1gqoLgvnkprl1f7sBNvYF1wNglv/6QcG47adEL8dD/yPAl5WpA1BPJCEq7aE41aHENQ/x5xkRd/YpH6ZOSxXJbdGesNhek+ocGL0YfnElnNFa8fvRK8XQzLMryDruaViiIMu3GS4PVLwopRYk5+xK8nwMHMH9CkcTiZs3itevNadVnhNfnHcqTpszEJTZn1NlfFPGmhjOd50R8ku0KwDdL+nex8w0NUDx3/cY06m9imVx7ZpkV+qL396I2I6S3+LlsxzzCERSdbdwR2tUlBa6MMrIikp8sbhFB5h1LFoItVfRATHE95
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
