apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background  # Avoid orphaned childs
spec:
  project: default
  sources:
    - chart: gateway-helm
      repoURL: docker.io/envoyproxy
      targetRevision: v1.7.0
    - repoURL: https://github.com/testdotcom/k8s-homelab.git
      targetRevision: HEAD
      path: argocd-apps/charts/gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:  # Enable Continuos Deployment (instead of Continuos Delivery)
      prune: true # Delete corresponding K8s resources if removed from Git
      selfHeal: true  # Rollback manual changes (avoid config drift)
    retry:  # Handle transient failures
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Avoid the 262,144-byte annotation size limit
