apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webserver
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background  # Avoid orphaned childs
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/testdotcom/k8s-homelab.git
    targetRevision: HEAD
    path: argocd-apps/charts/webserver
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-webserver
  syncPolicy:
    automated:  # Enable Continuos Deployment (instead of Continuos Delivery)
      prune: true # Delete corresponding K8s resources if removed from Git
      selfHeal: true  # Rollback manual changes (avoid config drift)
    retry:  # Handle transient failures
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
